"""initial schema

Revision ID: 7ff4628ae5cf
Revises: 
Create Date: 2026-09-28 20:24:17.169589

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '7ff4628ae5cf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account_groups')),
    sa.UniqueConstraint('name', name=op.f('uq_account_groups_name'))
    )
    op.create_table('bots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('bot_username', sa.String(length=64), nullable=True),
    sa.Column('bot_tg_id', sa.BigInteger(), nullable=True),
    sa.Column('token_enc', sa.Text(), nullable=False),
    sa.Column('webhook_secret', sa.String(length=64), nullable=False),
    sa.Column('webhook_enabled', sa.Boolean(), nullable=False),
    sa.Column('webhook_set_at', sa.String(length=64), nullable=True),
    sa.Column('relay_target_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('relay_target_kind', sa.Enum('group', 'private', name='relay_target_kind'), nullable=False),
    sa.Column('relay_enabled', sa.Boolean(), nullable=False),
    sa.Column('auto_reply_enabled', sa.Boolean(), nullable=False),
    sa.Column('persona_text', sa.Text(), nullable=False),
    sa.Column('remark', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bots')),
    sa.UniqueConstraint('name', name=op.f('uq_bots_name'))
    )
    op.create_table('proxies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('scheme', sa.String(length=16), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('username_enc', sa.Text(), nullable=True),
    sa.Column('password_enc', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('remark', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proxies')),
    sa.UniqueConstraint('name', name=op.f('uq_proxies_name'))
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'operator', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('tg_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone_enc', sa.Text(), nullable=True),
    sa.Column('phone_masked', sa.String(length=32), nullable=False),
    sa.Column('tg_user_id', sa.BigInteger(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('age_days', sa.Integer(), nullable=True),
    sa.Column('group_count', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('proxy_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'healthy', 'needs_code', 'frozen', 'invalid', 'dead', 'disabled', name='account_status'), nullable=False),
    sa.Column('status_reason', sa.String(length=255), nullable=False),
    sa.Column('current_task', sa.Enum('idle', 'syncing', 'awaiting_confirm', 'relaying', name='current_task'), nullable=False),
    sa.Column('session_enc', sa.Text(), nullable=True),
    sa.Column('authorized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=512), nullable=False),
    sa.Column('remark', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['account_groups.id'], name=op.f('fk_tg_accounts_group_id_account_groups'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['proxy_id'], ['proxies.id'], name=op.f('fk_tg_accounts_proxy_id_proxies'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tg_accounts')),
    sa.UniqueConstraint('tg_user_id', name='uq_tg_accounts_tg_user_id')
    )
    op.create_index(op.f('ix_tg_accounts_status'), 'tg_accounts', ['status'], unique=False)
    op.create_index(op.f('ix_tg_accounts_tg_user_id'), 'tg_accounts', ['tg_user_id'], unique=False)
    op.create_table('account_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['tg_accounts.id'], name=op.f('fk_account_assignments_account_id_tg_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_account_assignments_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account_assignments')),
    sa.UniqueConstraint('user_id', 'account_id', name='uq_account_assignments_user_account')
    )
    op.create_index(op.f('ix_account_assignments_account_id'), 'account_assignments', ['account_id'], unique=False)
    op.create_index(op.f('ix_account_assignments_user_id'), 'account_assignments', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('bot_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('client_ip', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['tg_accounts.id'], name=op.f('fk_audit_logs_account_id_tg_accounts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], name=op.f('fk_audit_logs_bot_id_bots'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_account_id'), 'audit_logs', ['account_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_created_action', 'audit_logs', ['created_at', 'action'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('dialogs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Enum('user_account', 'bot', name='dialog_channel'), nullable=False),
    sa.Column('kind', sa.Enum('private', 'group', name='dialog_kind'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('bot_id', sa.UUID(), nullable=True),
    sa.Column('tg_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('member_count', sa.Integer(), nullable=True),
    sa.Column('peer_display', sa.String(length=255), nullable=False),
    sa.Column('unread_count', sa.Integer(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_message_preview', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['tg_accounts.id'], name=op.f('fk_dialogs_account_id_tg_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], name=op.f('fk_dialogs_bot_id_bots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dialogs')),
    sa.UniqueConstraint('account_id', 'tg_chat_id', name='uq_dialogs_account_chat'),
    sa.UniqueConstraint('bot_id', 'tg_chat_id', name='uq_dialogs_bot_chat')
    )
    op.create_index(op.f('ix_dialogs_account_id'), 'dialogs', ['account_id'], unique=False)
    op.create_index(op.f('ix_dialogs_bot_id'), 'dialogs', ['bot_id'], unique=False)
    op.create_index(op.f('ix_dialogs_channel'), 'dialogs', ['channel'], unique=False)
    op.create_index(op.f('ix_dialogs_kind'), 'dialogs', ['kind'], unique=False)
    op.create_index(op.f('ix_dialogs_last_message_at'), 'dialogs', ['last_message_at'], unique=False)
    op.create_index(op.f('ix_dialogs_tg_chat_id'), 'dialogs', ['tg_chat_id'], unique=False)
    op.create_table('leases',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('worker_id', sa.String(length=128), nullable=False),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['tg_accounts.id'], name=op.f('fk_leases_account_id_tg_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('account_id', name=op.f('pk_leases'))
    )
    op.create_index(op.f('ix_leases_lease_until'), 'leases', ['lease_until'], unique=False)
    op.create_index(op.f('ix_leases_worker_id'), 'leases', ['worker_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dialog_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Enum('user_account', 'bot', name='dialog_channel'), nullable=False),
    sa.Column('direction', sa.Enum('incoming', 'outgoing', name='message_direction'), nullable=False),
    sa.Column('status', sa.Enum('received', 'pending', 'sent', 'failed', name='message_status'), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('tg_message_id', sa.BigInteger(), nullable=True),
    sa.Column('sender_tg_id', sa.BigInteger(), nullable=True),
    sa.Column('sender_name', sa.String(length=255), nullable=False),
    sa.Column('reply_to_tg_message_id', sa.BigInteger(), nullable=True),
    sa.Column('has_media', sa.Boolean(), nullable=False),
    sa.Column('media_type', sa.String(length=32), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_messages_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dialog_id'], ['dialogs.id'], name=op.f('fk_messages_dialog_id_dialogs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index('ix_messages_dialog_created', 'messages', ['dialog_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_messages_dialog_id'), 'messages', ['dialog_id'], unique=False)
    op.create_index(op.f('ix_messages_direction'), 'messages', ['direction'], unique=False)
    op.create_index('uq_messages_dialog_tg_message', 'messages', ['dialog_id', 'tg_message_id'], unique=True, postgresql_where=sa.text('tg_message_id IS NOT NULL'))
    op.create_table('relay_routes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('bot_id', sa.UUID(), nullable=False),
    sa.Column('staff_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('staff_chat_title', sa.String(length=255), nullable=False),
    sa.Column('target_kind', sa.Enum('group', 'private', name='relay_target_kind'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('dialog_id', sa.UUID(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['tg_accounts.id'], name=op.f('fk_relay_routes_account_id_tg_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], name=op.f('fk_relay_routes_bot_id_bots'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_relay_routes_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dialog_id'], ['dialogs.id'], name=op.f('fk_relay_routes_dialog_id_dialogs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_relay_routes'))
    )
    op.create_index(op.f('ix_relay_routes_bot_id'), 'relay_routes', ['bot_id'], unique=False)
    op.create_index(op.f('ix_relay_routes_staff_chat_id'), 'relay_routes', ['staff_chat_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('sync_dialogs', 'sync_messages', 'send_message', 'account_check', 'update_profile', 'login_start', 'login_code', 'login_password', 'relay_to_staff', 'bot_reply', 'reply_to_origin', name='task_type'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'pending_confirmation', 'running', 'completed', 'failed', 'cancelled', name='task_status'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('bot_id', sa.UUID(), nullable=True),
    sa.Column('dialog_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('worker_id', sa.String(length=128), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('dedupe_key', sa.String(length=160), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['tg_accounts.id'], name=op.f('fk_tasks_account_id_tg_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], name=op.f('fk_tasks_bot_id_bots'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_tasks_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dialog_id'], ['dialogs.id'], name=op.f('fk_tasks_dialog_id_dialogs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks')),
    sa.UniqueConstraint('dedupe_key', name=op.f('uq_tasks_dedupe_key'))
    )
    op.create_index(op.f('ix_tasks_account_id'), 'tasks', ['account_id'], unique=False)
    op.create_index('ix_tasks_account_status', 'tasks', ['account_id', 'status'], unique=False)
    op.create_index(op.f('ix_tasks_bot_id'), 'tasks', ['bot_id'], unique=False)
    op.create_index('ix_tasks_bot_status', 'tasks', ['bot_id', 'status'], unique=False)
    op.create_index('ix_tasks_claim', 'tasks', ['status', 'next_run_at', 'priority'], unique=False)
    op.create_index(op.f('ix_tasks_next_run_at'), 'tasks', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_type'), 'tasks', ['type'], unique=False)
    op.create_index(op.f('ix_tasks_worker_id'), 'tasks', ['worker_id'], unique=False)
    op.create_table('relay_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('route_id', sa.UUID(), nullable=True),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('bot_id', sa.UUID(), nullable=False),
    sa.Column('staff_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('staff_message_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], name=op.f('fk_relay_links_bot_id_bots'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_relay_links_message_id_messages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['route_id'], ['relay_routes.id'], name=op.f('fk_relay_links_route_id_relay_routes'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_relay_links')),
    sa.UniqueConstraint('message_id', name=op.f('uq_relay_links_message_id'))
    )
    op.create_index('uq_relay_links_staff_message', 'relay_links', ['staff_chat_id', 'staff_message_id'], unique=True)
    op.create_table('reply_drafts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dialog_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'sent', 'discarded', name='draft_status'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('sent_by', sa.UUID(), nullable=True),
    sa.Column('sent_message_id', sa.UUID(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_reply_drafts_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dialog_id'], ['dialogs.id'], name=op.f('fk_reply_drafts_dialog_id_dialogs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sent_by'], ['users.id'], name=op.f('fk_reply_drafts_sent_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sent_message_id'], ['messages.id'], name=op.f('fk_reply_drafts_sent_message_id_messages'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reply_drafts'))
    )
    op.create_index(op.f('ix_reply_drafts_dialog_id'), 'reply_drafts', ['dialog_id'], unique=False)
    op.create_index(op.f('ix_reply_drafts_status'), 'reply_drafts', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reply_drafts_status'), table_name='reply_drafts')
    op.drop_index(op.f('ix_reply_drafts_dialog_id'), table_name='reply_drafts')
    op.drop_table('reply_drafts')
    op.drop_index('uq_relay_links_staff_message', table_name='relay_links')
    op.drop_table('relay_links')
    op.drop_index(op.f('ix_tasks_worker_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_type'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_next_run_at'), table_name='tasks')
    op.drop_index('ix_tasks_claim', table_name='tasks')
    op.drop_index('ix_tasks_bot_status', table_name='tasks')
    op.drop_index(op.f('ix_tasks_bot_id'), table_name='tasks')
    op.drop_index('ix_tasks_account_status', table_name='tasks')
    op.drop_index(op.f('ix_tasks_account_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_relay_routes_staff_chat_id'), table_name='relay_routes')
    op.drop_index(op.f('ix_relay_routes_bot_id'), table_name='relay_routes')
    op.drop_table('relay_routes')
    op.drop_index('uq_messages_dialog_tg_message', table_name='messages', postgresql_where=sa.text('tg_message_id IS NOT NULL'))
    op.drop_index(op.f('ix_messages_direction'), table_name='messages')
    op.drop_index(op.f('ix_messages_dialog_id'), table_name='messages')
    op.drop_index('ix_messages_dialog_created', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_leases_worker_id'), table_name='leases')
    op.drop_index(op.f('ix_leases_lease_until'), table_name='leases')
    op.drop_table('leases')
    op.drop_index(op.f('ix_dialogs_tg_chat_id'), table_name='dialogs')
    op.drop_index(op.f('ix_dialogs_last_message_at'), table_name='dialogs')
    op.drop_index(op.f('ix_dialogs_kind'), table_name='dialogs')
    op.drop_index(op.f('ix_dialogs_channel'), table_name='dialogs')
    op.drop_index(op.f('ix_dialogs_bot_id'), table_name='dialogs')
    op.drop_index(op.f('ix_dialogs_account_id'), table_name='dialogs')
    op.drop_table('dialogs')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_action', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_account_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_account_assignments_user_id'), table_name='account_assignments')
    op.drop_index(op.f('ix_account_assignments_account_id'), table_name='account_assignments')
    op.drop_table('account_assignments')
    op.drop_index(op.f('ix_tg_accounts_tg_user_id'), table_name='tg_accounts')
    op.drop_index(op.f('ix_tg_accounts_status'), table_name='tg_accounts')
    op.drop_table('tg_accounts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('proxies')
    op.drop_table('bots')
    op.drop_table('account_groups')
    # ### end Alembic commands ###
