"""Pydantic schema 统一出口。"""

from __future__ import annotations

from app.schemas.account import (
    AccountCreate,
    AccountListResponse,
    AccountOut,
    AccountSummary,
    AccountUpdate,
    AssignableAccounts,
    AssignmentCreate,
    AssignmentOut,
    CheckRequest,
    CheckResultOut,
    GroupCreate,
    GroupOut,
    GroupUpdate,
    LoginCodeRequest,
    LoginPasswordRequest,
    LoginStartRequest,
    LoginStepResponse,
    ProxyCreate,
    ProxyOut,
    ProxyUpdate,
)
from app.schemas.audit import (
    AuditListResponse,
    AuditOut,
    DashboardOut,
    FailedTaskOut,
    WorkerStatus,
)
from app.schemas.auth import (
    LoginRequest,
    TokenResponse,
    UserCreate,
    UserOut,
    UserUpdate,
)
from app.schemas.common import OkResponse, ORMModel, Page, PageQuery
from app.schemas.dialog import (
    DialogListResponse,
    DialogOut,
    DraftOut,
    DraftRequest,
    MessageListResponse,
    MessageOut,
    SendMessageRequest,
    SendMessageResponse,
    SyncDialogsRequest,
    SyncMessagesRequest,
)
from app.schemas.relay import (
    BotCreate,
    BotOut,
    BotUpdate,
    RelayLinkOut,
    RelayRouteCreate,
    RelayRouteOut,
    RelayRouteUpdate,
    WebhookResult,
)
from app.schemas.task import (
    TaskActionResponse,
    TaskCreateRequest,
    TaskListResponse,
    TaskOut,
)

__all__ = [
    "ORMModel",
    "Page",
    "PageQuery",
    "OkResponse",
    "LoginRequest",
    "TokenResponse",
    "UserOut",
    "UserCreate",
    "UserUpdate",
    "AccountCreate",
    "AccountUpdate",
    "AccountOut",
    "AccountSummary",
    "AccountListResponse",
    "LoginStartRequest",
    "LoginStepResponse",
    "LoginCodeRequest",
    "LoginPasswordRequest",
    "CheckRequest",
    "CheckResultOut",
    "GroupCreate",
    "GroupUpdate",
    "GroupOut",
    "ProxyCreate",
    "ProxyUpdate",
    "ProxyOut",
    "AssignmentCreate",
    "AssignmentOut",
    "AssignableAccounts",
    "DialogOut",
    "DialogListResponse",
    "MessageOut",
    "MessageListResponse",
    "SendMessageRequest",
    "SendMessageResponse",
    "SyncDialogsRequest",
    "SyncMessagesRequest",
    "DraftRequest",
    "DraftOut",
    "TaskOut",
    "TaskListResponse",
    "TaskCreateRequest",
    "TaskActionResponse",
    "BotCreate",
    "BotUpdate",
    "BotOut",
    "RelayRouteCreate",
    "RelayRouteUpdate",
    "RelayRouteOut",
    "RelayLinkOut",
    "WebhookResult",
    "AuditOut",
    "AuditListResponse",
    "DashboardOut",
    "WorkerStatus",
    "FailedTaskOut",
]
