/**
 * token → antd v5 ConfigProvider。
 *
 * 单独成文件的原因：tokens.ts 保持「零运行时依赖」的纯数据，
 * 这样换皮/生成 CSS 兜底块时可以直接用 node 读取（无需打包 antd）。
 *
 * 设计原则：能用 token 表达的全部显式指定，避免 antd 用算法派生出
 * 「另一个蓝 / 另一个灰」，从而保证 antd 组件与自研组件在同一套色板里。
 */
import { theme as antdTheme, type ThemeConfig } from 'antd';
import { tokensFor, type ThemeMode } from './tokens';

export function antdThemeFor(mode: ThemeMode): ThemeConfig {
  const t = tokensFor(mode);
  const c = t.color;
  const isDark = mode === 'dark';

  return {
    algorithm: isDark ? antdTheme.darkAlgorithm : antdTheme.defaultAlgorithm,
    token: {
      colorPrimary: c.primary,
      colorInfo: c.info,
      colorSuccess: c.success,
      colorWarning: c.warning,
      colorError: c.danger,
      colorLink: c.textLink,
      colorLinkHover: c.textLinkHover,

      colorBgBase: c.bgApp,
      colorTextBase: c.textPrimary,
      colorBgLayout: c.bgApp,
      colorBgContainer: c.bgCard,
      colorBgElevated: c.bgElevated,
      colorBgSpotlight: c.tooltipBg,
      colorBgMask: c.bgMask,
      colorFillQuaternary: c.bgHover,
      colorFillTertiary: c.bgHover,
      colorFillSecondary: c.bgActive,
      colorFill: c.borderStrong,

      colorBorder: c.border,
      colorBorderSecondary: c.borderSubtle,
      colorSplit: c.divider,

      colorText: c.textPrimary,
      colorTextSecondary: c.textSecondary,
      colorTextTertiary: c.textTertiary,
      colorTextQuaternary: c.textDisabled,
      colorTextDisabled: c.textDisabled,
      colorTextPlaceholder: c.textTertiary,
      colorTextHeading: c.textPrimary,
      colorIcon: c.textTertiary,
      colorIconHover: c.textPrimary,

      fontFamily: t.font.family,
      fontFamilyCode: t.font.familyMono,
      fontSize: t.font.size,
      fontSizeSM: t.font.sizeSm,
      fontSizeLG: t.font.sizeLg,
      fontSizeXL: t.font.sizeXl,
      fontSizeHeading1: t.font.sizeDisplay,
      fontSizeHeading2: 24,
      fontSizeHeading3: t.font.sizeTitle,
      fontSizeHeading4: t.font.sizeLg,
      fontSizeHeading5: t.font.size,
      lineHeight: t.font.lineNormal,

      borderRadius: t.radius.control,
      borderRadiusXS: t.radius.xs,
      borderRadiusSM: t.radius.sm,
      borderRadiusLG: t.radius.card,
      borderRadiusOuter: t.radius.card,

      controlHeight: t.layout.controlHeight,
      controlHeightSM: t.layout.controlHeightSm,
      controlHeightLG: t.layout.controlHeightLg,
      controlHeightXS: 22,
      lineWidth: 1,

      boxShadow: t.shadow.md,
      boxShadowSecondary: t.shadow.lg,
      boxShadowTertiary: t.shadow.sm,

      motionDurationFast: `${t.motion.durationFast}ms`,
      motionDurationMid: `${t.motion.durationBase}ms`,
      motionDurationSlow: `${t.motion.durationSlow}ms`,

      zIndexBase: t.zIndex.base,
      zIndexPopupBase: t.zIndex.modal,

      wireframe: false,
      sizeUnit: 4,
      sizeStep: 4,
      padding: 16,
      margin: 16,
    },
    components: {
      Layout: {
        bodyBg: c.bgApp,
        headerBg: c.bgTopbar,
        headerHeight: t.layout.topbarHeight,
        headerPadding: `0 ${t.layout.contentPaddingX}px`,
        siderBg: c.bgSider,
        triggerBg: c.bgSiderHover,
        triggerColor: c.textSecondary,
        footerBg: c.bgSunken,
      },
      Menu: {
        itemBg: 'transparent',
        subMenuItemBg: 'transparent',
        itemColor: c.textSecondary,
        itemHoverColor: c.textPrimary,
        itemHoverBg: c.bgHover,
        itemSelectedColor: c.primary,
        itemSelectedBg: c.bgSiderActive,
        itemActiveBg: c.bgActive,
        itemHeight: 38,
        itemMarginInline: 8,
        itemMarginBlock: 2,
        itemBorderRadius: t.radius.control,
        itemPaddingInline: 10,
        iconSize: 16,
        collapsedIconSize: 18,
        iconMarginInlineEnd: 10,
        groupTitleColor: c.textTertiary,
        groupTitleFontSize: t.font.sizeXs,
        groupTitleLineHeight: 1.6,
        activeBarWidth: 0,
        activeBarBorderWidth: 0,
        subMenuItemBorderRadius: t.radius.sm,
        horizontalItemSelectedColor: c.primary,
        darkItemBg: 'transparent',
        darkSubMenuItemBg: 'transparent',
        darkItemColor: c.textSecondary,
        darkItemHoverColor: c.textPrimary,
        darkItemHoverBg: c.bgHover,
        darkItemSelectedColor: c.primary,
        darkItemSelectedBg: c.bgSiderActive,
        darkGroupTitleColor: c.textTertiary,
      },
      Card: {
        colorBgContainer: c.bgCard,
        headerBg: 'transparent',
        headerFontSize: t.font.size,
        headerHeight: 48,
        headerHeightSM: 40,
        paddingLG: t.layout.cardPadding,
        bodyPadding: t.layout.cardPadding,
        bodyPaddingSM: 12,
        borderRadiusLG: t.radius.card,
        colorBorderSecondary: c.borderSubtle,
        boxShadowTertiary: 'none',
      },
      Table: {
        headerBg: c.bgSunken,
        headerColor: c.textSecondary,
        headerSplitColor: 'transparent',
        headerBorderRadius: 0,
        borderColor: c.divider,
        colorBgContainer: c.bgCard,
        rowHoverBg: c.bgHover,
        rowSelectedBg: c.bgSelected,
        rowSelectedHoverBg: c.primaryBg,
        cellPaddingBlock: 12,
        cellPaddingInline: 14,
        cellPaddingBlockMD: 10,
        cellPaddingInlineMD: 12,
        cellPaddingBlockSM: 8,
        cellPaddingInlineSM: 10,
        cellFontSize: t.font.size,
        cellFontSizeMD: t.font.size,
        cellFontSizeSM: t.font.sizeSm,
        footerBg: c.bgSunken,
        stickyScrollBarBg: c.borderStrong,
        expandIconBg: c.bgCard,
        selectionColumnWidth: 40,
      },
      Button: {
        fontWeight: t.font.weightMedium,
        primaryShadow: 'none',
        defaultShadow: 'none',
        dangerShadow: 'none',
        borderRadius: t.radius.control,
        borderRadiusSM: t.radius.sm,
        borderRadiusLG: t.radius.lg,
        paddingInline: 14,
        paddingInlineSM: 10,
        contentFontSize: t.font.size,
        defaultBg: c.bgCard,
        defaultColor: c.textPrimary,
        defaultBorderColor: c.border,
        defaultHoverBg: c.bgCardHover,
        defaultHoverBorderColor: c.primaryBorder,
        defaultHoverColor: c.primary,
        defaultActiveBorderColor: c.primary,
        defaultActiveColor: c.primaryActive,
        textHoverBg: c.bgHover,
        colorPrimaryHover: c.primaryHover,
        colorPrimaryActive: c.primaryActive,
        primaryColor: c.onPrimary,
      },
      Input: {
        colorBgContainer: c.bgInput,
        activeBorderColor: c.primary,
        hoverBorderColor: c.primaryBorder,
        activeShadow: 'none',
        errorActiveShadow: 'none',
        warningActiveShadow: 'none',
        paddingBlock: 6,
        paddingInline: 11,
        inputFontSize: t.font.size,
        colorTextPlaceholder: c.textTertiary,
      },
      InputNumber: { colorBgContainer: c.bgInput, activeShadow: 'none' },
      Select: {
        colorBgContainer: c.bgInput,
        optionSelectedBg: c.bgSelected,
        optionSelectedColor: c.primary,
        optionSelectedFontWeight: t.font.weightMedium,
        optionActiveBg: c.bgHover,
        optionPadding: '7px 12px',
        controlHeight: t.layout.controlHeight,
      },
      DatePicker: { colorBgContainer: c.bgInput, activeShadow: 'none' },
      Modal: {
        contentBg: c.bgElevated,
        headerBg: c.bgElevated,
        titleColor: c.textPrimary,
        titleFontSize: t.font.sizeLg,
        borderRadiusLG: t.radius.cardLg,
        footerBg: 'transparent',
        paddingContentHorizontalLG: t.space.xxxl,
      },
      Drawer: {
        colorBgElevated: c.bgElevated,
        footerPaddingBlock: t.space.lg,
        footerPaddingInline: t.space.xxl,
      },
      Tabs: {
        itemColor: c.textSecondary,
        itemHoverColor: c.textPrimary,
        itemSelectedColor: c.primary,
        inkBarColor: c.primary,
        titleFontSize: t.font.size,
        horizontalItemPadding: '10px 0',
        horizontalItemGutter: 24,
        verticalItemPadding: '8px 12px',
      },
      Tag: {
        defaultBg: c.neutralBg,
        defaultColor: c.neutral,
        borderRadiusSM: t.radius.sm,
        fontSizeSM: t.font.sizeSm,
        lineHeightSM: 1.5,
      },
      Tooltip: {
        colorBgSpotlight: c.tooltipBg,
        colorTextLightSolid: c.tooltipText,
        borderRadius: t.radius.md,
      },
      Dropdown: { paddingBlock: 6, borderRadiusLG: t.radius.lg, controlItemBgHover: c.bgHover },
      Breadcrumb: {
        itemColor: c.textTertiary,
        lastItemColor: c.textPrimary,
        linkColor: c.textTertiary,
        linkHoverColor: c.primary,
        separatorColor: c.textDisabled,
        fontSize: t.font.sizeSm,
      },
      Pagination: {
        itemActiveBg: c.primaryBg,
        itemBg: 'transparent',
        itemSize: 30,
        itemSizeSM: 26,
      },
      Segmented: {
        trackBg: c.bgSunken,
        itemColor: c.textSecondary,
        itemHoverColor: c.textPrimary,
        itemSelectedBg: c.bgCard,
        itemSelectedColor: c.textPrimary,
        trackPadding: 3,
        borderRadius: t.radius.control,
      },
      Descriptions: {
        labelBg: c.bgSunken,
        titleMarginBottom: t.space.md,
        itemPaddingBottom: t.space.lg,
        colonMarginRight: 8,
        contentColor: c.textPrimary,
        extraColor: c.textSecondary,
      },
      Statistic: {
        titleFontSize: t.font.sizeSm,
        contentFontSize: t.font.sizeDisplay,
      },
      Alert: {
        borderRadiusLG: t.radius.lg,
        withDescriptionPadding: '12px 16px',
        defaultPadding: '8px 12px',
      },
      Badge: { dotSize: 7, textFontSize: t.font.sizeSm, indicatorHeight: 18 },
      Progress: { defaultColor: c.primary, remainingColor: c.bgActive, lineBorderRadius: t.radius.pill },
      Skeleton: { blockRadius: t.radius.md, color: c.bgSkeleton, colorGradientEnd: c.skeletonHighlight },
      Empty: { colorTextDescription: c.textTertiary },
      Form: {
        labelColor: c.textSecondary,
        labelFontSize: t.font.size,
        itemMarginBottom: t.space.xxl,
        verticalLabelPadding: '0 0 6px',
        labelColonMarginInlineEnd: 8,
      },
      Divider: { colorSplit: c.divider, textPaddingInline: t.space.lg },
      Switch: { colorPrimary: c.primary, colorPrimaryHover: c.primaryHover },
      Checkbox: { borderRadiusSM: t.radius.xs },
      Radio: { buttonSolidCheckedBg: c.primary },
      Message: { contentBg: c.bgElevated, colorText: c.textPrimary, contentPadding: '10px 16px' },
      Notification: { colorBgElevated: c.bgElevated, paddingContentHorizontal: t.space.xxl },
      Popover: { colorBgElevated: c.bgElevated, borderRadiusLG: t.radius.lg },
      Steps: {
        colorPrimary: c.primary,
        colorTextDescription: c.textTertiary,
        iconSize: 26,
        titleLineHeight: 26,
      },
      Result: { titleFontSize: t.font.sizeTitle, subtitleFontSize: t.font.size },
      Spin: { colorPrimary: c.primary },
      Anchor: { colorPrimary: c.primary },
    },
  };
}
